### PR TITLE
add etcd systemd service name and refactor kitchen tests

### PR DESCRIPTION
**Pull request by willejs**
This PR does the following:
- [x] Uses fixture cookbook to run integration tests and simplify kitchen
- [x] Uses supermarket cookbooks for etcd and docker
- [x] Upgrade to latest and greatest etcd cookbook
- [x] move to inspec tests to test install as well as kubernetes functionality

### CODE REVIEW

**Comment by willejs** [comment]
@jpgriffo @odacremolbap what do you think about this?

**Comment by willejs** [comment]
@smartinm

**Comment by smartinm** [comment]
Thanks! Your PR's looks nice, we'll give it some testing.

**Comment by smartinm** [comment]
I have make some changes in willejs-refactor branch to get tests to work and add a recipe to install etcd service.

**Comment by willejs** [comment]
@smartinm I beat you to it i think? ;) 
Does yours look the same?

**Comment by willejs** [comment]
@smartinm Did you manage to look at this and try to test it?
What do you think?

**Comment by willejs** [comment]
@smartinm @jpgriffo @odacremolbap can you review please?

**Comment by runningman84** [comment]
@smartinm @jpgriffo @odacremolbap any news here?

**Comment by willejs** [comment]
@smartinm @jpgriffo @odacremolbap ive tried really hard here to contribute and improve your cookbook, but im going to close this pr now and maintain my own fork. I am going to refactor the whole cookbook into custom resources and write tests and make a solid robust cookbook.

**Comment by runningman84** [comment]
@willejs I am looking forward to test your own fork!

**Pull request closed without merging**
